---
# Global configuration for Hermes
# ======================================

# System configuration
hermes_timezone: UTC
hermes_locale: en_US.UTF-8

# Common role configuration
common_hostname: "{{ inventory_hostname }}"
common_timezone: "{{ hermes_timezone }}"
common_install_packages: []
common_disable_unused_services:
  - bluetooth
  - ModemManager
  - cups
  - cups-browsed
  - avahi-daemon
  - triggerhappy
  - dphys-swapfile
  - hciuart
  - wpa_supplicant

# Network configuration
hermes_domain: hermes.local

# Unbound DNS Server Configuration
# ===============================

# Local zones for internal domain resolution
unbound_local_zones:
  - name: "{{ hermes_domain }}"
    type: static
    records:
      - "{{ hermes_domain }}. IN A {{ ansible_default_ipv4.address }}"
  - name: "dedale.local"
    type: static
    records:
      - "dedale.local. IN A 192.168.1.5"
# AdGuard Home configuration
adguard_version: "v0.107.66"
adguard_local_dns_enabled: true
adguard_local_dns_records:
  - domain: "*.sagradafamilia.casa"
    ip: "192.168.1.7"

# Firewall configuration
firewall_allowed_ports:
  - port: 22
    proto: tcp
  - port: 53
    proto: udp
  - port: 53
    proto: tcp
  - port: 80
    proto: tcp
  - port: 443
    proto: tcp
  - port: 8080
    proto: tcp
  - port: 45876
    proto: tcp

# Synchronization settings
firewall_sync_enabled: true  # Enable complete UFW rules synchronization

# Security role configuration
security_ssh_password_auth: true

# System updates role configuration
system_updates_check_kernel: true
system_updates_check_eeprom: true
system_updates_upgrade_packages: true
system_updates_clean_cache: true

# Nginx reverse proxy configuration
proxies:
  - subdomain: home
    host: 192.168.1.5
    port: "8081"
    template_file: "generic-proxy"
    enabled: true

  # Hermes
  - subdomain: "adguard"
    host: "127.0.0.1"
    port: "8080"
    template_file: "adguard"
    enabled: true

  # Home Assistant
  - subdomain: "ha"
    host: 192.168.1.2
    port: "8123"
    template_file: homeassistant
    enabled: true

  # Dedale
  - subdomain: "unifi"
    host: "192.168.1.5"
    port: "8443"
    template_file: "unifi"
    enabled: true
  - subdomain: "portainer"
    host: "192.168.1.5"
    port: "9443"
    template_file: "portainer"
    enabled: true
  - subdomain: "speedtest"
    host: "192.168.1.5"
    port: "8082"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "dashboard"
    host: "192.168.1.5"
    port: "8083"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "beszel"
    host: "192.168.1.5"
    port: "8090"
    template_file: "beszel-proxy"
    enabled: true

  # TrueNas
  - subdomain: "nas"
    host: "192.168.1.6"
    port: "80"
    template_file: "truenas"
    enabled: true
  - subdomain: "jellyfin"
    host: "192.168.1.6"
    port: "8096"
    template_file: "jellyfin"
    enabled: true
  - subdomain: "jellyseerr"
    host: "192.168.1.6"
    port: "5055"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "sonarr"
    host: "192.168.1.6"
    port: "8989"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "radarr"
    host: "192.168.1.6"
    port: "7878"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "bazarr"
    host: "192.168.1.6"
    port: "6767"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "readarr"
    host: "192.168.1.6"
    port: "8787"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "jackett"
    host: "192.168.1.6"
    port: "9117"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "deluge"
    host: "192.168.1.6"
    port: "8112"
    template_file: "generic-proxy"
    enabled: true
  - subdomain: "nzb"
    host: "192.168.1.6"
    port: "6789"
    template_file: "generic-proxy"
    enabled: true

  # Heimdall
  - subdomain: "uptime"
    host: "192.168.1.4"
    port: "3001"
    template_file: "uptime"
    enabled: true

  # Thot
  - subdomain: "z2m"
    host: "192.168.1.3"
    port: "8080"
    template_file: "zigbee2mqtt"
    enabled: true
  - subdomain: "ntfy"
    host: "192.168.1.3"
    port: "8081"
    template_file: "ntfy"
    enabled: true

# Tailscale configuration
tailscale_enabled: true
tailscale_advertise_routes:
  - "192.168.1.0/24"
tailscale_accept_routes: true

# Beszel Agent Configuration
# ==========================

# Beszel hub URL (required for agent connection)
beszel_agent_hub_url: "https://beszel.sagradafamilia.casa"

# Beszel agent configuration (only overriding non-defaults)
beszel_agent_public_key: "{{ vault_beszel_agent_public_key | default('') }}"
beszel_agent_token: "{{ vault_beszel_agent_token | default('') }}"
