---
all:
  hosts:
    hermes:
      ansible_host: 192.168.1.7
      ansible_user: pi
      ansible_ssh_private_key_file: >-
        {{ vault_ssh_private_key_file | default('~/.ssh/alepieser') }}
      ansible_python_interpreter: /usr/bin/python3
