---
# Let's Encrypt configuration
letsencrypt_email: "{{ vault_letsencrypt_email | default('admin@example.com') }}"
letsencrypt_domain: "{{ vault_letsencrypt_domain | default('example.com') }}"
letsencrypt_wildcard: "{{ vault_letsencrypt_wildcard | default('*.example.com') }}"

# Certbot configuration
certbot_install_dir: /opt/certbot
certbot_config_dir: /etc/letsencrypt
certbot_webroot_dir: /var/www/certbot
certbot_renewal_hook: /etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh

# ACME server configuration
certbot_cloudflare_acme_server: "https://acme-v02.api.letsencrypt.org/directory"

# Auto-renewal configuration
certbot_auto_renew: true
certbot_renewal_cron_hour: "3"
certbot_renewal_cron_minute: "0"
