---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    daemon_reload: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true

- name: Restart certbot
  ansible.builtin.systemd:
    name: certbot.timer
    state: restarted
    daemon_reload: true
