---
name: Ansible

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare cache directories
        run: |
          mkdir -p ~/.cache/pip
          mkdir -p ~/.ansible/roles
          mkdir -p ~/.ansible/collections

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Cache Ansible Galaxy
        uses: actions/cache@v4
        with:
          path: |
            ~/.ansible/roles
            ~/.ansible/collections
          key: ${{ runner.os }}-galaxy-${{ hashFiles('requirements.yml') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Check playbook syntax
        run: ansible-playbook --syntax-check playbooks/setup.yml

      - name: Lint with ansible-lint
        run: ansible-lint

      - name: Lint with yamllint
        run: yamllint .
